version: "3.9"

services:
  db:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.postgres
    container_name: points-postgres
    env_file:
      - configs/.env.example
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: "redis:latest"
    container_name: points-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: [ "redis-server", "--requirepass", "redispassword" ]

volumes:
  db-data:
  redis-data:
