version: "3.9"

services:
  db:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.postgres
    container_name: points-postgres
    env_file:
      - configs/.env.example
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: "redis:latest"
    container_name: points-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: [ "redis-server", "--requirepass", "redispassword" ]
  app:
      build:
        context: .
        dockerfile: ./docker/Dockerfile.app
      container_name: points-app
      env_file:
        - configs/.env.example
      ports:
        - "8080:8080"
      depends_on:
        - db
        - redis

volumes:
  db-data:
  redis-data:
