version: "3.9"

services:
  db:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.postgres
    container_name: points-db
    env_file:
      - configs/.env.example
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
