// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package orm

import (
	"time"
)

const TableNameTransactionEvent = "transaction_event"

// TransactionEvent mapped from table <transaction_event>
type TransactionEvent struct {
	ID            int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TransactionID string    `gorm:"column:transaction_id;not null" json:"transaction_id"`
	EventType     string    `gorm:"column:event_type;not null" json:"event_type"`
	Payload       string    `gorm:"column:payload" json:"payload"`
	CreatedAt     time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName TransactionEvent's table name
func (*TransactionEvent) TableName() string {
	return TableNameTransactionEvent
}
